question_data = [
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
         "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "How old is Chloe Price in Life is Strange: Before the Storm?", "correct_answer": "16",
         "incorrect_answers": ["24", "19", "15"]},
        {"type": "multiple", "difficulty": "hard", "category": "History",
         "question": "On which day did ARPANET suffer a 4 hour long network crash?",
         "correct_answer": "October 27, 1980",
         "incorrect_answers": ["November 21, 1969", "October 29, 1969", "December 9, 1991"]},
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "Which of the following is not a real Pok&eacute;mon?", "correct_answer": "Luminid",
         "incorrect_answers": ["Dragalge", "Mandibuzz", "Araquanid"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Board Games",
         "question": "When Magic: The Gathering was first solicited, which of the following was it originally titled?",
         "correct_answer": "Mana Clash", "incorrect_answers": ["Magic", "Magic Clash", "Mana Duels"]},
        {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
         "question": "What is the name given to Indian food cooked over charcoal in a clay oven?",
         "correct_answer": "Tandoori", "incorrect_answers": ["Biryani", "Pani puri", "Tiki masala"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
         "question": "Nick Mason is the only member to appear on every Pink Floyd album.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "What was the first interactive movie video game?", "correct_answer": "Astron Belt",
         "incorrect_answers": ["Dragon&#039;s Lair", "Cube Quest", "M.A.C.H. 3"]}]
